name: Rebuild with upstream updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_versions_and_rebuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: upstream_versions
      - name: Check for upstream updates
        run: pip install requests && python .github/workflows/check_upstream_versions.py
        if: ${{ failure() }}
      - uses: actions/upload-artifact@v2
        with:
          name: upstream_versions
          path: upstream_versions
      - name: Rebuild image to include updates
        if: ${{ env.REBUILD == 'true' }}
        run: echo "I'd be rebuilding now."
