name: Rebuild with upstream updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_versions_and_rebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux-arm-v7, linux-arm64, linux-amd64]

    steps:
      - uses: actions/checkout@v2

      - name: Check for upstream updates
        run: pip install docker requests && python .github/workflows/check_upstream_versions.py

      - name: Rebuild image to include updates
        if: ${{ env.REBUILD == 'true' }}
        run: echo "I'd be rebuilding now."

      - name: Set up Docker Buildx
        if: ${{ env.REBUILD == 'true' }}
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to DockerHub
        if: ${{ env.REBUILD == 'true' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build images using buildx
        if: ${{ env.REBUILD == 'true' }}
        run: |
          ARCHITECTURE=${{ matrix.architecture }}
          docker buildx build \
            --cache-from "${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-cache-${ARCHITECTURE}" \
            --cache-to "${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-cache-${ARCHITECTURE}" \
            --platform ${ARCHITECTURE//-/\/} \
            --output "type=image,push=true" \
            --tag ${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${ARCHITECTURE} \
            --file ./Dockerfile ./
